services:
  # 1) Front‑end  (SSR build; change if you export statically)
  - type: web
    name: mcbot-frontend
    env: node
    plan: free                # or 'starter'
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start            # Next.js serves on $PORT
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: mcbot-api
          property: url          # auto‑injects https://mcbot-api.onrender.com

  # 2) Back‑end
  - type: web
    name: mcbot-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY           # fill in Render dashboard
      - key: MONGO_USER               # "
      - key: MONGO_PASSWORD           # "
      - key: MONGO_CLUSTER_URL        # "
