services:
  # 1) Back‑end -------------------------------------------------------------
  - type: web
    name: mcbot-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false          # Render will ask for the value
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_CLUSTER_URL
        sync: false

  # 2) Front‑end -----------------------------------------------------------
  - type: web
    name: mcbot-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      # Render injects the API’s internal host:port value.
      # Your Next.js code can build the full URL with:
      #   const apiBase = `https://${process.env.NEXT_PUBLIC_API_HOSTPORT}`;
      - key: NEXT_PUBLIC_API_HOSTPORT
        fromService:
          type: web
          name: mcbot-api
          property: hostport
